# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
# samples: config/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# 

units: config/units.tsv
peak_comparison: config/peak_comparisons.tsv
sample_comparison: config/sample_comparisons.yaml

ref:
  # Ensembl species name
  species: 
    - homo_sapiens
    - sars_cov2
    - homo_sapiens_sars_cov2
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 
    homo_sapiens: "106"
    sars_cov2: "MN908947.3"
  # Genome build
  build: 
    homo_sapiens: "GRCh38"
    sars_cov2: "NC_045512.2"
  fasta:
    homo_sapiens: "references/fasta/Homo_sapiens.GRCh38.dna_sm.toplevel.fa"
    sars_cov2: "references/fasta/Sars_cov_2.ASM985889v3.dna.toplevel.fa"
    only_sars_cov2: "references/fasta/Sars_cov_2.ASM985889v3.dna.toplevel.fa"
    homo_sapiens_sars_cov2: "references/fasta/GRCh38_SarsCov2.dna.toplevel.fa"
    repbase: "references/fasta/RMRBSeqs.fasta"
    silva: "references/fasta/SILVA_ref.fa"
  gtf:
    homo_sapiens: "references/gtf/Homo_sapiens.GRCh38.106.gtf"
    sars_cov2: "references/gtf/Sars_cov_2.ASM985889v3.101.gtf"
    homo_sapiens_sars_cov2: "references/gtf/GRCh38_SarsCov2.gtf"
  length:
    only_sars_cov2: 29903
  host: "homo_sapiens"
  virus: "sars_cov2"

align-order-input:
  sars_cov2: "results/star/homo_sapiens"
  homo_sapiens_sars_cov2: "results/trimmed/round2"

report:
  organisms: 
    - homo_sapiens_sars_cov2
    - only_sars_cov2

subgenome:
  "sars_cov2": "MN908947.3"
  "homo_sapines": "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 MT X Y"

trimming:
  activate: False

params:
  cutadapt-pe-round1: "--match-read-wildcards --times 1 -e 0.1 -O 1 --quality-cutoff 6 -m 18 -a NNNNNAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -g CTTCCGATCTACAAGTT -g CTTCCGATCTTGGTCCT -A AACTTGTAGATCGGA -A AGGACCAAGATCGGA -A ACTTGTAGATCGGAA -A GGACCAAGATCGGAA -A CTTGTAGATCGGAAG -A GACCAAGATCGGAAG -A TTGTAGATCGGAAGA -A ACCAAGATCGGAAGA -A TGTAGATCGGAAGAG -A CCAAGATCGGAAGAG -A GTAGATCGGAAGAGC -A CAAGATCGGAAGAGC -A TAGATCGGAAGAGCG -A AAGATCGGAAGAGCG -A AGATCGGAAGAGCGT -A GATCGGAAGAGCGTC -A ATCGGAAGAGCGTCG -A TCGGAAGAGCGTCGT -A CGGAAGAGCGTCGTG -A GGAAGAGCGTCGTGT"
  cutadapt-pe-round2: "--match-read-wildcards --times 1 -e 0.1 -O 5 --quality-cutoff 6 -m 18 -A AACTTGTAGATCGGA -A AGGACCAAGATCGGA -A ACTTGTAGATCGGAA -A GGACCAAGATCGGAA -A CTTGTAGATCGGAAG -A GACCAAGATCGGAAG -A TTGTAGATCGGAAGA -A ACCAAGATCGGAAGA -A TGTAGATCGGAAGAG -A CCAAGATCGGAAGAG -A GTAGATCGGAAGAGC -A CAAGATCGGAAGAGC -A TAGATCGGAAGAGCG -A AAGATCGGAAGAGCG -A AGATCGGAAGAGCGT -A GATCGGAAGAGCGTC -A ATCGGAAGAGCGTCG -A TCGGAAGAGCGTCGT -A CGGAAGAGCGTCGTG -A GGAAGAGCGTCGTGT"
  star-index-homo_sapiens: "--genomeSAindexNbases 12 --sjdbGTFfeatureExon exon --sjdbGTFtagExonParentGene gene_id --sjdbGTFtagExonParentTranscript transcript_id --sjdbOverhang 29 --limitIObufferSize 30000000 50000000"
  star-index-homo_sapiens_sars_cov2: "--genomeSAindexNbases 12 --sjdbGTFfeatureExon exon --sjdbGTFtagExonParentGene gene_id --sjdbGTFtagExonParentTranscript transcript_id --sjdbOverhang 29 --limitIObufferSize 30000000 50000000"
  star-index-sars_cov2: "--genomeSAindexNbases 6 --sjdbGTFfeatureExon exon --sjdbGTFtagExonParentGene gene_id --sjdbGTFtagExonParentTranscript transcript_id --sjdbOverhang 29"
  star-index-silva: "--genomeSAindexNbases 14 --genomeChrBinNbits 10 "
  star-index-repbase: "--genomeSAindexNbases 12 --genomeChrBinNbits 11 "
  star-map-homo_sapiens: "--runMode alignReads --outFilterMultimapScoreRange 1 --outFilterType Normal --outFilterScoreMin 10 --outSAMtype BAM SortedByCoordinate --alignEndsType EndToEnd --alignIntronMin 20 --alignIntronMax 10000 --outSAMattributes All --outSAMstrandField intronMotif --sjdbGTFfeatureExon exon --sjdbGTFtagExonParentGene gene_id --sjdbGTFtagExonParentTranscript transcript_id --alignSoftClipAtReferenceEnds No --limitBAMsortRAM 3500191063 --outReadsUnmapped Fastx "
  star-map-sars_cov2: "--runMode alignReads --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outFilterMatchNmin 0 --outSAMtype BAM SortedByCoordinate --outFilterMultimapNmax 1 --outFilterMultimapScoreRange 1 --outSAMattributes All --outFilterType Normal --sjdbGTFfeatureExon exon --sjdbGTFtagExonParentGene gene_id --sjdbGTFtagExonParentTranscript transcript_id --alignSoftClipAtReferenceEnds No --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNoverLmax 0.04 --scoreDelOpen -1 --alignIntronMin 20 --alignIntronMax 3000 --alignMatesGapMax 3000 --alignEndsType EndToEnd --limitBAMsortRAM 1100191063 --outReadsUnmapped Fastx"  
  star-map-homo_sapiens_sars_cov2: "--runMode alignReads --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outFilterMatchNmin 0 --outSAMtype BAM SortedByCoordinate --outFilterMultimapNmax 1 --outFilterMultimapScoreRange 1 --outSAMattributes All --outFilterType Normal --sjdbGTFfeatureExon exon --sjdbGTFtagExonParentGene gene_id --sjdbGTFtagExonParentTranscript transcript_id --alignSoftClipAtReferenceEnds No --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNoverLmax 0.04 --scoreDelOpen -1 --alignIntronMin 20 --alignIntronMax 3000 --alignMatesGapMax 3000 --alignEndsType EndToEnd --limitBAMsortRAM 110000000000 --outReadsUnmapped Fastx"  
  star-map-silva: "--runMode alignReads --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outSAMattributes All --outSAMtype BAM Unsorted --outFilterType Normal --alignEndsType EndToEnd --seedPerWindowNmax 5 --alignSoftClipAtReferenceEnds No --limitBAMsortRAM 1100191063 --outReadsUnmapped Fastx"
  star-map-lenti: "--runMode alignReads --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outSAMattributes All --outSAMtype BAM Unsorted --outFilterType Normal --alignEndsType EndToEnd --seedPerWindowNmax 5 --alignSoftClipAtReferenceEnds No --limitBAMsortRAM 1100191063 --outReadsUnmapped Fastx"
  star-map-repbase: "--runMode alignReads --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outSAMattributes All --outSAMtype BAM Unsorted --outFilterType Normal --alignEndsType EndToEnd --seedPerWindowNmax 5 --alignSoftClipAtReferenceEnds No --limitBAMsortRAM 1100191063 --outReadsUnmapped Fastx "
  star-index-homo_sapiens-ram: 350000000000
  star-index-homo_sapiens_sars_cov2-ram: 350000000000
  star-map-homo_sapiens-ram: 320000000000
  star-map-homo_sapiens_sars_cov2-ram: 320000000000
  star-map-sars_cov2-ram: 100000000000
  star-map-repbase-ram: 100000000000
  star-map-silva-ram: 100000000000
  macs-sars_cov2: "-g 29716"
  macs-only_sars_cov2: "-f BAM -g 29903 -s 31 --verbose 2 --keep-dup all --nomodel --d-min 25 --call-summits --scale-to small --shift 25 --nolambda --extsize 5 --max-gap 20 --min-length 5"
  macs-homo_sapiens: "-g hs"
  macs-homo_sapiens_sars_cov2: "-g hs"



